import type { WorkoutExerciseMediaSource } from "@/lib/workoutExercises";

export const EXERCISE_MEDIA_MAP: Record<string, WorkoutExerciseMediaSource> = {
  "ball__ball-between-thighs-plie": require("@/assets/exercises/demo/ball__ball-between-thighs-plie.jpg"),
  "ball__bridge-with-ball": require("@/assets/exercises/demo/ball__bridge-with-ball.jpg"),
  "ball__hundred-with-ball": require("@/assets/exercises/demo/ball__hundred-with-ball.jpg"),
  "barrel__side-stretch-on-barrel": require("@/assets/exercises/demo/barrel__side-stretch-on-barrel.jpg"),
  "barrel__spine-stretch-on-barrel": require("@/assets/exercises/demo/barrel__spine-stretch-on-barrel.jpg"),
  "barrel__swan-on-barrel": require("@/assets/exercises/demo/barrel__swan-on-barrel.jpg"),
  "breathing__breathing": require("@/assets/exercises/demo/breathing__breathing.jpg"),
  "breathing__breathing-on-reformer": require("@/assets/exercises/demo/breathing__breathing-on-reformer.jpg"),
  "breathing__breathing-with-arm-reach": require("@/assets/exercises/demo/breathing__breathing-with-arm-reach.jpg"),
  "breathing__cadillac-breathing": require("@/assets/exercises/demo/breathing__cadillac-breathing.jpg"),
  "breathing__diaphragmatic-breathing": require("@/assets/exercises/demo/breathing__diaphragmatic-breathing.jpg"),
  "breathing__lateral-breathing": require("@/assets/exercises/demo/breathing__lateral-breathing.jpg"),
  "breathing__percussive-breathing": require("@/assets/exercises/demo/breathing__percussive-breathing.jpg"),
  "breathing__rib-cage-breathing": require("@/assets/exercises/demo/breathing__rib-cage-breathing.jpg"),
  "cadillac__cadillac-breathing": require("@/assets/exercises/demo/cadillac__cadillac-breathing.jpg"),
  "cadillac__one-arm-roll-down": require("@/assets/exercises/demo/cadillac__one-arm-roll-down.jpg"),
  "cadillac__roll-down-rollback-bar": require("@/assets/exercises/demo/cadillac__roll-down-rollback-bar.jpg"),
  "chair__footwork-on-chair": require("@/assets/exercises/demo/chair__footwork-on-chair.jpg"),
  "chair__pump-seated": require("@/assets/exercises/demo/chair__pump-seated.jpg"),
  "chair__pump-standing": require("@/assets/exercises/demo/chair__pump-standing.jpg"),
  "magic-circle__bridge-with-circle-inner-thigh": require("@/assets/exercises/demo/magic-circle__bridge-with-circle-inner-thigh.jpg"),
  "magic-circle__hundred-with-magic-circle": require("@/assets/exercises/demo/magic-circle__hundred-with-magic-circle.jpg"),
  "magic-circle__rolling-like-a-ball-circle": require("@/assets/exercises/demo/magic-circle__rolling-like-a-ball-circle.jpg"),
  "mat__roll-over": require("@/assets/exercises/demo/mat__roll-over.jpg"),
  "mat__roll-up": require("@/assets/exercises/demo/mat__roll-up.jpg"),
  "mat__the-hundred": require("@/assets/exercises/demo/mat__the-hundred.jpg"),
  "reformer-advanced__corkscrew": require("@/assets/exercises/demo/reformer-advanced__corkscrew.jpg"),
  "reformer-advanced__snake": require("@/assets/exercises/demo/reformer-advanced__snake.jpg"),
  "reformer-advanced__snake-and-twist": require("@/assets/exercises/demo/reformer-advanced__snake-and-twist.jpg"),
  "reformer-core__footwork-arches": require("@/assets/exercises/demo/reformer-core__footwork-arches.jpg"),
  "reformer-core__footwork-heels": require("@/assets/exercises/demo/reformer-core__footwork-heels.jpg"),
  "reformer-core__footwork-toes": require("@/assets/exercises/demo/reformer-core__footwork-toes.jpg"),
  "reformer-longbox__pull-straps": require("@/assets/exercises/demo/reformer-longbox__pull-straps.jpg"),
  "reformer-longbox__swan-on-long-box": require("@/assets/exercises/demo/reformer-longbox__swan-on-long-box.jpg"),
  "reformer-longbox__t-pull": require("@/assets/exercises/demo/reformer-longbox__t-pull.jpg"),
  "reformer-rowing__rowing-90-degrees": require("@/assets/exercises/demo/reformer-rowing__rowing-90-degrees.jpg"),
  "reformer-rowing__rowing-from-the-chest": require("@/assets/exercises/demo/reformer-rowing__rowing-from-the-chest.jpg"),
  "reformer-rowing__rowing-into-the-sternum": require("@/assets/exercises/demo/reformer-rowing__rowing-into-the-sternum.jpg"),
  "reformer-shortbox__short-box-flat": require("@/assets/exercises/demo/reformer-shortbox__short-box-flat.jpg"),
  "reformer-shortbox__short-box-round": require("@/assets/exercises/demo/reformer-shortbox__short-box-round.jpg"),
  "reformer-shortbox__short-box-side-to-side": require("@/assets/exercises/demo/reformer-shortbox__short-box-side-to-side.jpg"),
  "reformer-straps__feet-in-straps-circles": require("@/assets/exercises/demo/reformer-straps__feet-in-straps-circles.jpg"),
  "reformer-straps__feet-in-straps-frogs": require("@/assets/exercises/demo/reformer-straps__feet-in-straps-frogs.jpg"),
  "reformer-straps__feet-in-straps-lower-lift": require("@/assets/exercises/demo/reformer-straps__feet-in-straps-lower-lift.jpg"),
  "reformer-stretch__down-stretch": require("@/assets/exercises/demo/reformer-stretch__down-stretch.jpg"),
  "reformer-stretch__long-stretch": require("@/assets/exercises/demo/reformer-stretch__long-stretch.jpg"),
  "reformer-stretch__up-stretch": require("@/assets/exercises/demo/reformer-stretch__up-stretch.jpg"),
};

